#!/usr/bin/env bash
# installs nginx and starts the web server.
#!/bin/bash

apt-get update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default
service nginx restart
