#!/usr/bin/env bash
# installs and starts Nginx web server

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
echo "Hello World!" | sudo tee /var/www/html/index.html \
	> /dev/null
sudo sed -i 's|/var/www/html|/var/www/html/index.html|' \
	/etc/nginx/sites-available/default
sudo service nginx start
