#!/usr/bin/env bash
# indefinitely prints 'To infinity and beyond' 
# and when a SIGTERM signal is received, prints 'I am invicible'

trap "echo I am invincible!!!" SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
