#!/usr/bin/env bash
# configures Ubuntu server. Resolves `localhost` to `127.0.0.2`
# and `facebook` to `8.8.8.8`

# create a backup
# edit `hosts` file
# cp /etc/hosts /etc/hosts_backup
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
sed -i '$a 8.8.8.8 	facebook.com' /etc/hosts
