#!/usr/bin/env bash
# configures Ubuntu server. Resolves `localhost` to `127.0.0.2`
# and `facebook` to `8.8.8.8`

# create a backup
# edit `hosts` file
cp /etc/hosts ~/hosts_backup
sed -i '$a 127.0.0.2	localhost' /etc/hosts
sed -i '$a 8.8.8.8	facebook.com' /etc/hosts
